# Generated by Django 5.2.8 on 2026-05-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
    ]
